name: deep
dependencies:
- python=2.7.14
- Jinja2
- MarkupSafe
- certifi
- ipython
- matplotlib
- mock
- nose
- numpy
- pyparsing
- python-dateutil
- pytz
- pyzmq
- scipy
- six
- tornado
- wsgiref
- readline
- jupyter
- notebook
